version: "3.5"
services:
  keycloak-postgres:
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  keycloak:
    build: .
    hostname: keycloak
    ports:
      - 8080:8080
      - 8787:8787
      - 9990:9990
      - 8443:8443
    environment:
      KC_DB: POSTGRES
      KC_DB_URL_HOST: keycloak-postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      DEBUG: 'true'
      DEBUG_PORT: '*:8787'
    depends_on:
      - keycloak-postgres