version: '3.5'

services:
  postgres:
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  keycloak:
    image: jboss/keycloak:12.0.1
    volumes:
      - ../cqdg-keycloak-themes/src/main/resources/theme/cqdg:/opt/jboss/keycloak/themes/cqdg
      - ../cqdg-keycloak-themes/src/main/resources/theme/cqdg-admin:/opt/jboss/keycloak/themes/cqdg-admin
      - ../cqdg-keycloak-themes/src/main/resources/theme/main:/opt/jboss/keycloak/themes/main
      - ./standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml
      - ./standalone-ha.xml:/opt/jboss/keycloak/standalone/configuration/standalone-ha.xml
      - ../target/standalone/deployments:/opt/jboss/keycloak/standalone/deployments
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      DEBUG: 'true'
      DEBUG_PORT: '*:8787'
    ports:
      - 8080:8080
      - 8787:8787
      - 9990:9990
    depends_on:
      - postgres