version: '3.5'

services:
  keycloak-postgres:
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  keycloak:
    image: ferlabcrsj/cqdg-keycloak:ba49d1571670f92d5f157e8128d5756fe0999277
    volumes:
      - ../cqdg-keycloak-themes/src/main/resources/theme/cqdg:/opt/jboss/keycloak/themes/cqdg
      - ../cqdg-keycloak-themes/src/main/resources/theme/cqdg-admin:/opt/jboss/keycloak/themes/cqdg-admin
      - ../cqdg-keycloak-themes/src/main/resources/theme/main:/opt/jboss/keycloak/themes/main
      - ../target/standalone/deployments:/opt/jboss/keycloak/standalone/deployments
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      DEBUG: 'true'
      DEBUG_PORT: '*:8787'
      ORCID_URL: 'https://sandbox.orcid.org'
    ports:
      - 8080:8080
      - 8787:8787
      - 9990:9990
    depends_on:
      - keycloak-postgres